---
- name: Deploy Next.js Application
  hosts: servers
  become: true
  vars:
    ghcr_username: "m4nojTudu"
    ghcr_password: "{{ lookup('env', 'GHCR_PAT') }}"
    domain_suffix: "server.awr360.help"
    sanitized_branch_name: "{{ lookup('env', 'SANITIZED_BRANCH_NAME') }}"

  tasks:
    - name: Ensure Docker and Docker Compose are installed
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Ensure Docker Compose is installed via pip
      pip:
        name: docker-compose
        state: latest

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Create a directory for Traefik
      file:
        path: /opt/traefik
        state: directory

    - name: Create Traefik configuration file
      copy:
        dest: /opt/traefik/traefik.yml
        content: |
          entryPoints:
            web:
              address: ":80"
          providers:
            docker:
              endpoint: "unix:///var/run/docker.sock"
              exposedByDefault: false
          api:
            dashboard: true

    - name: Create Docker Compose file for Traefik
      copy:
        dest: /opt/traefik/docker-compose.yml
        content: |
          version: '3.8'
          services:
            traefik:
              image: traefik:v2.4
              command:
                - "--api.insecure=true"
                - "--providers.docker=true"
                - "--entrypoints.web.address=:80"
              ports:
                - "80:80"
                - "8080:8080"
              volumes:
                - "/var/run/docker.sock:/var/run/docker.sock"
              networks:
                - web
          networks:
            web:

    - name: Start Traefik
      command: /usr/local/bin/docker-compose up -d
      args:
        chdir: /opt/traefik

    - name: Log in to GitHub Container Registry
      shell: |
        echo "{{ ghcr_password }}" | docker login ghcr.io -u {{ ghcr_username }} --password-stdin
      ignore_errors: yes

    - name: Run Docker container
      shell: |
        INTERNAL_PORT=$((3000 + RANDOM % 1000))
        docker run -d \
          --name admin-{{ sanitized_branch_name }} \
          --label "traefik.enable=true" \
          --label "traefik.http.routers.{{ sanitized_branch_name }}.rule=Host(`{{ sanitized_branch_name }}.{{ domain_suffix }}`)" \
          --label "traefik.http.services.{{ sanitized_branch_name }}.loadbalancer.server.port=3000" \
          --network web \
          -p $INTERNAL_PORT:3000 \
          ghcr.io/{{ ghcr_username }}/admin:{{ sanitized_branch_name }}
      environment:
        SANITIZED_BRANCH_NAME: "{{ sanitized_branch_name }}"
